---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ochotierras/api.ochotierras.cl/
    - cd $DEPLOYPATH
    - /opt/cpanel/ea-php82/root/usr/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan migrate --force
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan config:cache
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan route:cache
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan view:cache
    - /opt/cpanel/ea-php82/root/usr/bin/php artisan storage:link
